name: Python application

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  build:
    name: Python Build
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'trigger_pipeline'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"
      - name: Install dependencies
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: dependencies and set up unit test
        run: |
          cd dockerfile 
          python3.10 -m pip install -r requirements.txt
          cd ..
      - name: install thermoxels
        run: python3.10 -m pip install -e .
      - name: Test with unittest
        run: |
          python3.10 -m unittest discover tests
